import "../styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <div
          className="w-full h-full backdrop-brightness-50 backdrop-blur-xl"
          style={{
            background: "linear-gradient(90deg,#e52e71,#ff8a00)",
          }}
        >
          {children}
        </div>
      </body>
    </html>
  );
}
