import "../styles/global.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className="min-h-screen"
        style={{ backgroundImage: `url("images/img1.jpg")` }}
      >
        <div className="w-full h-full backdrop-brightness-50 backdrop-blur-xl">
          {children}
        </div>
      </body>
    </html>
  );
}
